version: "3.9"

services:
  app:
    container_name: app-dev
    image: app-dev
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true